# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc5bd2b9faeefa22425a02c30459967afcf3faaac09952555576d22f9ae8839d8cb7394c56c10a5ba3f7a98203c207972ab3bf00967733205c70792dc318fae2

test:
  secret_key_base: edb836d870f5f6285636285dfac41685c9e2f535c3b458c009441f6c56c708cfd97fa44715745ca68e3834ba82d68f205d37caa178c3e8ba37767db07ddd87e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
